'use client'
import { useState } from 'react'
import { PropertyInput, createProperty, updateProperty } from '@/app/actions/properties'
import { Loader2, X } from 'lucide-react'
import { useRouter } from 'next/navigation'

interface PropertyFormProps { property?: PropertyInput & { id?: number }; onClose?: () => void }
const TYPES = ['Villa', 'Apartment', 'Plot', 'Farm Land', 'Commercial']
const STATUSES = ['available', 'sold', 'rented', 'under-construction']
export function PropertyForm({ property: initialProperty, onClose }: PropertyFormProps) {
  const empty: PropertyInput = { code: '', name: '', location: '', price: 0, size: '', type: 'Villa', description: '', imageUrl: '', status: 'available' }
  const [formData, setFormData] = useState<PropertyInput>(initialProperty || empty), [loading, setLoading] = useState(false), [error, setError] = useState('')
  const router = useRouter()
  async function submit(e: React.FormEvent) { e.preventDefault(); setLoading(true); setError(''); try { initialProperty?.id ? await updateProperty(initialProperty.id, formData) : await createProperty(formData); onClose?.(); router.refresh() } catch (err) { setError(err instanceof Error ? err.message : 'Failed to save property') } finally { setLoading(false) } }
  const field = (label: string, key: keyof PropertyInput, type = 'text', placeholder = '') => <label className="flex flex-col gap-2 text-sm font-medium text-foreground">{label}<input type={type} value={String(formData[key] ?? '')} onChange={(e) => setFormData({ ...formData, [key]: type === 'number' ? Number(e.target.value) : e.target.value })} placeholder={placeholder} className="w-full rounded-lg border border-border bg-input px-3 py-2 font-normal outline-none focus:border-primary" required={!['code', 'description', 'imageUrl'].includes(key)} /></label>
  return <div className="card-luxury border border-border p-6"><div className="mb-6 flex items-center justify-between"><h2 className="text-2xl font-bold">{initialProperty?.id ? 'Edit Property' : 'Add New Property'}</h2>{onClose && <button onClick={onClose} aria-label="Close"><X /></button>}</div><form onSubmit={submit} className="flex flex-col gap-4">{error && <p className="rounded-lg border border-destructive/20 bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}<div className="grid gap-4 md:grid-cols-2">{field('Property Code', 'code', 'text', 'e.g. PROP-001')}{field('Property Name *', 'name', 'text', 'Luxury Villa')}{field('Location *', 'location', 'text', 'Hyderabad, Telangana')}{field('Price (INR) *', 'price', 'number', '10000000')}{field('Size *', 'size', 'text', '2500 sq.ft')}{<label className="flex flex-col gap-2 text-sm font-medium">Type<select value={formData.type} onChange={(e) => setFormData({ ...formData, type: e.target.value })} className="rounded-lg border border-border bg-input px-3 py-2">{TYPES.map((x) => <option key={x}>{x}</option>)}</select></label>}{<label className="flex flex-col gap-2 text-sm font-medium">Status<select value={formData.status} onChange={(e) => setFormData({ ...formData, status: e.target.value })} className="rounded-lg border border-border bg-input px-3 py-2">{STATUSES.map((x) => <option key={x}>{x}</option>)}</select></label>}</div><label className="flex flex-col gap-2 text-sm font-medium">Description<textarea value={formData.description ?? ''} onChange={(e) => setFormData({ ...formData, description: e.target.value })} rows={4} className="rounded-lg border border-border bg-input px-3 py-2" /></label><label className="flex flex-col gap-2 text-sm font-medium">Image URLs <span className="text-xs font-normal text-muted-foreground">One HTTPS URL per line or comma-separated. Google Drive share links are converted automatically; set files to Anyone with the link.</span><textarea value={formData.imageUrl ?? ''} onChange={(e) => setFormData({ ...formData, imageUrl: e.target.value })} rows={4} placeholder="https://..." className="rounded-lg border border-border bg-input px-3 py-2" /></label><button disabled={loading} className="button-primary flex items-center justify-center gap-2 bg-primary text-primary-foreground disabled:opacity-50">{loading && <Loader2 className="animate-spin" />} {initialProperty?.id ? 'Update Property' : 'Add Property'}</button></form></div>
}
